name: ZETA-Hordes
main: me.pacdev.zeta_hordes.Main
version: Z1.4.0
api-version: 1.21
commands:
  zetahordes:
    description: Zeta Hordes command
    usage: /zetahordes
    permission: zeta.hordes
author: "Pacdev (Laut Khatulistiwa)"
