name: ZETA-Hordes
main: me.pacdev.zeta_hordes.Main
version: Z1.2.4
api-version: 1.18
commands:
  zetahordes:
    description: Zeta Hordes command
    usage: /zetahordes
    permission: zeta.hordes
author: "Pacdev (Laut Khatulistiwa)"